// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAsSpJNj5xzWCI1UxAEvNiZ5DIFJndhVe8',
//     appId: '1:285054194060:web:1234567890abcdef',
//     messagingSenderId: '285054194060',
//     projectId: 'applink-d7c5c',
//     authDomain: 'applink-d7c5c.firebaseapp.com',
//     storageBucket: 'applink-d7c5c.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAsSpJNj5xzWCI1UxAEvNiZ5DIFJndhVe8',
//     appId: '1:285054194060:android:d07e5dd3f18909271ac6a9',
//     messagingSenderId: '285054194060',
//     projectId: 'applink-d7c5c',
//     storageBucket: 'applink-d7c5c.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAsSpJNj5xzWCI1UxAEvNiZ5DIFJndhVe8',
//     appId: '1:285054194060:ios:XXXXXXXXXXXXXXXX',
//     messagingSenderId: '285054194060',
//     projectId: 'applink-d7c5c',
//     storageBucket: 'applink-d7c5c.firebasestorage.app',
//     iosBundleId: 'com.example.comparisonApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAsSpJNj5xzWCI1UxAEvNiZ5DIFJndhVe8',
//     appId: '1:285054194060:macos:XXXXXXXXXXXXXXXX',
//     messagingSenderId: '285054194060',
//     projectId: 'applink-d7c5c',
//     storageBucket: 'applink-d7c5c.firebasestorage.app',
//     iosBundleId: 'com.example.comparisonApp',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAsSpJNj5xzWCI1UxAEvNiZ5DIFJndhVe8',
//     appId: '1:285054194060:windows:XXXXXXXXXXXXXXXX',
//     messagingSenderId: '285054194060',
//     projectId: 'applink-d7c5c',
//     authDomain: 'applink-d7c5c.firebaseapp.com',
//     storageBucket: 'applink-d7c5c.firebasestorage.app',
//   );
// }
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// New Added Nimita
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZF8rUNmH_4EgIomD1ZVbmRV7LluDRImw',
    appId: '1:406538002309:web:a1b2c3d4e5f67890',
    messagingSenderId: '406538002309',
    projectId: 'price-comparison-30109',
    authDomain: 'price-comparison-30109.firebaseapp.com',
    storageBucket: 'price-comparison-30109.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-HpvmoLON6iCbmaxPx-QY-U_Zyq3_kv8',
    appId: '1:757101401778:android:5af60c1851d6eee8ef5bab',
    messagingSenderId: '757101401778',
    projectId: 'ai-enhancer-b4c47',
    storageBucket: 'ai-enhancer-b4c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZF8rUNmH_4EgIomD1ZVbmRV7LluDRImw',
    appId: '1:406538002309:ios:b1c2d3e4f5a67890',
    messagingSenderId: '406538002309',
    projectId: 'price-comparison-30109',
    storageBucket: 'price-comparison-30109.firebasestorage.app',
    iosBundleId: 'com.example.comparisonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZF8rUNmH_4EgIomD1ZVbmRV7LluDRImw',
    appId: '1:406538002309:macos:c1d2e3f4a5b67890',
    messagingSenderId: '406538002309',
    projectId: 'price-comparison-30109',
    storageBucket: 'price-comparison-30109.firebasestorage.app',
    iosBundleId: 'com.example.comparisonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZF8rUNmH_4EgIomD1ZVbmRV7LluDRImw',
    appId: '1:406538002309:windows:d1e2f3a4b5c67890',
    messagingSenderId: '406538002309',
    projectId: 'price-comparison-30109',
    authDomain: 'price-comparison-30109.firebaseapp.com',
    storageBucket: 'price-comparison-30109.firebasestorage.app',
  );
}
